build(release): Missing line continuation
    + ./.tox/build/bin/towncrier build
    Loading template...
    Finding news fragments...
    Rendering news fragments...
    Writing to newsfile...
    Staging newsfile...
    Removing news fragments...
    I want to remove the following files:
    /home/runner/work/python-project-structure/python-project-structure/src/pythonprojectstructure/newsfragments/008.misc.rst
    Aborted!
    /home/runner/work/python-project-structure/python-project-structure/src/pythonprojectstructure/newsfragments/003.misc.rst
    /home/runner/work/python-project-structure/python-project-structure/src/pythonprojectstructure/newsfragments/007.misc.rst
    /home/runner/work/python-project-structure/python-project-structure/src/pythonprojectstructure/newsfragments/002.misc.rst
    /home/runner/work/python-project-structure/python-project-structure/src/pythonprojectstructure/newsfragments/005.misc.rst
    /home/runner/work/python-project-structure/python-project-structure/src/pythonprojectstructure/newsfragments/004.misc.rst
    /home/runner/work/python-project-structure/python-project-structure/src/pythonprojectstructure/newsfragments/001.misc.rst
    make[1]: *** [Makefile:114: release-python] Error 1
    make: *** [Makefile:95: release] Error 2
    Is it okay if I remove those files? [Y/n]: make[1]: Leaving directory '/home/runner/work/python-project-structure/python-project-structure'
    Error: Process completed with exit code 2.