build(python): Missing required host packages
Encountered on GitLab CI:

    + docker buildx build --pull --tag merpatterson/python-project-structure:0.7.1 --tag merpatterson/python-project-structure:0.7 --tag merpatterson/python-project-structure:0 --tag merpatterson/python-project-structure:latest ./
    bash: line 9: docker: command not found
    make: *** [Makefile:302: var/log/docker-build.log] Error 127
    make: *** Deleting file 'var/log/docker-build.log'
    Cleaning up project directory and file based variables
    ERROR: Job failed: exit code 1