build(docker): Compose pulled image volume perms
When compose is run using a pulled image, as opposed to one built locally, we need to
ensure the volumes are owned by the user just as we do when building an image.  This is
particularly relevant in CI/CD:

    + docker compose run --rm python-project-structure-devel pyproject-build -s
    Network python-project-structure_default  Creating
    Network python-project-structure_default  Created
    adduser: Warning: The home directory `/home/python-project-structure' does not belong to the user you are currently creating.
    * Creating venv isolated environment...
    * Installing packages in isolated environment... (setuptools>=45, setuptools_scm>=6.2, wheel)
    * Getting build dependencies for sdist...
    /tmp/build-env-tl0pen8j/lib/python3.11/site-packages/setuptools_scm/git.py:135: UserWarning: "/usr/local/src/python-project-structure" is shallow and may cause errors
      warnings.warn(f'"{wd.path}" is shallow and may cause errors')
    running egg_info
    error: Cannot update time stamp of directory 'src/python_project_structure.egg-info'

    ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
    make: *** [Makefile:403: release-python] Error 1