build(deps): Workaround pip dependency resolver
    ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    rstcheck 6.1.1 requires importlib-metadata<5.0,>=1.6; python_version < "3.8", but you have importlib-metadata 5.2.0 which is incompatible.
    rstcheck-core 1.0.3 requires importlib-metadata<5.0,>=1.6; python_version < "3.8", but you have importlib-metadata 5.2.0 which is incompatible.
    flake8 5.0.4 requires importlib-metadata<4.3,>=1.1.0; python_version < "3.8", but you have importlib-metadata 5.2.0 which is incompatible.

Resolving this issue downgrades `$ tox` which also requires removing a CLI option not
yet supported in that downgraded version.