build(base): Avoid previous tag clash on release
    + git push --no-verify --tags github HEAD:develop
    remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
    To https://github.com/rpatterson/prunerr.git
       305f6d9a..05f0a7b6  HEAD -> develop
     * [new tag]           v1.1.9b1 -> v1.1.9b1
     ! [rejected]          v1.1.9b0 -> v1.1.9b0 (already exists)
    error: failed to push some refs to 'https://github.com/rpatterson/prunerr.git'
    hint: Updates were rejected because the tag already exists in the remote.
    make: *** [Makefile:806: release-bump] Error 1