test(py): Missing full lint reports directory
    py311: commands[2]> pylint --output-format parseable:./build/reports/py311/pylint.parseable,json:./build/reports/py311/pylint.json,msvs:./build/reports/py311/pylint.msvs,colorized ./src/projectstructure/
    Traceback (most recent call last):
      File "/usr/local/src/project-structure/.tox/py311/bin/pylint", line 8, in <module>
        sys.exit(run_pylint())
                 ^^^^^^^^^^^^
      File "/usr/local/src/project-structure/.tox/py311/lib/python3.11/site-packages/pylint/__init__.py", line 36, in run_pylint
        PylintRun(argv or sys.argv[1:])
      File "/usr/local/src/project-structure/.tox/py311/lib/python3.11/site-packages/pylint/lint/run.py", line 169, in __init__
        args = _config_initialization(
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/project-structure/.tox/py311/lib/python3.11/site-packages/pylint/config/config_initialization.py", line 75, in _config_initialization
        parsed_args_list = linter._parse_command_line_configuration(args_list)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/project-structure/.tox/py311/lib/python3.11/site-packages/pylint/config/arguments_manager.py", line 278, in _parse_command_line_configuration
        self.config, parsed_args = self._arg_parser.parse_known_args(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/argparse.py", line 1902, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/argparse.py", line 2114, in _parse_known_args
        start_index = consume_optional(start_index)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/argparse.py", line 2054, in consume_optional
        take_action(action, args, option_string)
      File "/usr/local/lib/python3.11/argparse.py", line 1978, in take_action
        action(self, namespace, argument_values, option_string)
      File "/usr/local/src/project-structure/.tox/py311/lib/python3.11/site-packages/pylint/config/callback_actions.py", line 449, in __call__
        self.linter._load_reporters(values[0])
      File "/usr/local/src/project-structure/.tox/py311/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 435, in _load_reporters
        open(reporter_output[0], "w", encoding="utf-8")
    FileNotFoundError: [Errno 2] No such file or directory: './build/reports/py311/pylint.parseable'
    py311: exit 1 (0.55 seconds) /usr/local/src/project-structure> pylint --output-format parseable:./build/reports/py311/pylint.parseable,json:./build/reports/py311/pylint.json,msvs:./build/reports/py311/pylint.msvs,colorized ./src/projectstructure/ pid=197
    .pkg: _exit> python /home/project-structure/.local/pipx/venvs/tox/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
      py311: FAIL code 1 (11.77=setup[3.46]+cmd[7.51,0.26,0.55] seconds)
      evaluation failed :( (11.84 seconds)
    make: *** [Makefile:686: test-local] Error 1
    make[1]: *** [Makefile:746: test-docker-pyminor] Error 2
    make: *** [Makefile:737: test-docker-3.11] Error 2
    make[1]: Leaving directory '/__w/project-structure/project-structure'