build(release): Version bump running in container
Needs to be outside the container like other release tasks.  Specifically in this case,
can't commit in the container:

    + ./.tox/build/bin/towncrier build --version 0.6.2-beta.2 --yes
    Loading template...
    Finding news fragments...
    Rendering news fragments...
    Writing to newsfile...
    Staging newsfile...
    Removing news fragments...
    Removing the following files:
    /usr/local/src/python-project-structure/src/pythonprojectstructure/newsfragments/009.misc.rst
    /usr/local/src/python-project-structure/src/pythonprojectstructure/newsfragments/010.misc.rst
    /usr/local/src/python-project-structure/src/pythonprojectstructure/newsfragments/008.misc.rst
    error: the following files have changes staged in the index:
        src/pythonprojectstructure/newsfragments/009.misc.rst
        src/pythonprojectstructure/newsfragments/010.misc.rst
    (use --cached to keep the file, or -f to force removal)
    Done!
    + git commit --no-verify -S -m 'build(release): Update changelog v0.6.2-beta.1 -> v0.6.2-beta.2'
    Author identity unknown

    *** Please tell me who you are.

    Run

      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"

    to set your account's default identity.
    Omit --global to set the identity only in this repository.

    fatal: unable to auto-detect email address (got 'python-project-structure@88d80deb30ad.(none)')
    make: *** [Makefile:78: build-bump] Error 128
    make: *** [Makefile:262: var/log/docker-build.log] Error 2