ci(release): Wrong commit signing key
    + GIT_TRACE=1
    + git commit --no-verify -S -m 'build(release): Update changelog v0.6.0 -> v0.7.0'
    22:20:39.300212 git.c:460               trace: built-in: git commit --no-verify -S -m 'build(release): Update changelog v0.6.0 -> v0.7.0'
    22:20:39.301349 run-command.c:655       trace: run_command: gpg --status-fd=2 -bsau 'runner <runner@fv-az444-716.mvkj0dyzoqtu3fmr4yatzo1xtd.cx.internal.cloudapp.net>'
    error: gpg failed to sign the data
    fatal: failed to write commit object
    make: *** [Makefile:92: release-python] Error 128

This reverts commit 4da984af76efe0f6dfd7128ab4153c78fd5ff70f.