fix(portion): Handle items no selected files
When no files are selected the `portion` option for the item files `aggregation`
operation results in division by zero:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/pdb.py", line 1778, in main
        pdb._run(target)
      File "/usr/local/lib/python3.11/pdb.py", line 1646, in _run
        self.run(target.code)
      File "/usr/local/lib/python3.11/bdb.py", line 600, in run
        exec(cmd, globals, locals)
      File "<string>", line 1, in <module>
      File "/usr/local/bin/prunerr", line 8, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 272, in main
        _main(args=args)
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 319, in _main
        if (result := parsed_args.command(runner, **command_kwargs)) is not None:
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 212, in daemon
        runner.daemon(*args, **kwargs)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 384, in daemon
        self.exec_()
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 198, in exec_
        if free_space_results := self.free_space():
                                 ^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 350, in free_space
        download_clients = self.free_space_remove_items(download_clients, results)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 452, in free_space_remove_items
        for download_item in getattr(
                             ^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 376, in find_seeding
        return self.sort_items_by_tracker(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 186, in sort_items_by_tracker
        return sorted(
               ^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 382, in <genexpr>
        and self.operations.exec_indexer_operations(item)[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 103, in exec_indexer_operations
        include, sort_key = self.exec_operations(indexer_config["operations"], item)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 122, in exec_operations
        if (sort_value := executor(operation_config, item)) is None:
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 209, in exec_operation_files
        sort_value = sort_value / getattr(download_item, total)
                     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ZeroDivisionError: division by zero

Handle that gracefully by returning zero when the devisor is zero.