fix(history): Ignore release missing native dates
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/pdb.py", line 1723, in main
        pdb._runscript(mainpyfile)
      File "/usr/local/lib/python3.10/pdb.py", line 1583, in _runscript
        self.run(statement)
      File "/usr/local/lib/python3.10/bdb.py", line 598, in run
        exec(cmd, globals, locals)
      File "<string>", line 1, in <module>
      File "/usr/local/bin/prunerr", line 8, in <module>
        sys.exit(main())
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 210, in main
        _main(args=args)
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 265, in _main
        if (result := parsed_args.command(runner, **command_kwargs)) is not None:
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 132, in daemon
        runner.daemon(*args, **kwargs)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 307, in daemon
        self._daemon_inner(stages)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 468, in _daemon_inner
        return self.apply_(stages)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 262, in apply_
        if stage_results := self.apply_stage(stage):
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 445, in apply_stage
        if applier_results := prunerr_stage():
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 167, in __call__
        if not operations or not self.items:
      File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 204, in items
        if not (stage_items := list(stage_filter())):
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 280, in filter_seeding
        yield from servarr_download_client.filter_seeding()
      File "/usr/local/src/prunerr/src/prunerr/servarr/downloadclient.py", line 177, in filter_seeding
        and (now - history_record["date"]) > daemon_poll
    TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'str'