build(release): Upload existing release signatures
I misunderstood how twine handles this.  The when uploading to more than one package
index the signatures from the first upload are re-used for the second:

https://twine.readthedocs.io/en/stable/#why-should-i-use-this

+ ./.tox/build/bin/twine upload -s -r gitlab ./dist/python_project_structure-0.8.5-py3-none-any.whl ./dist/python-project-structure-0.8.5.tar.gz
Uploading distributions to
https://gitlab.com/api/v4/projects/41587336/packages/pypi
Signing python_project_structure-0.8.5-py3-none-any.whl
gpg: cannot open '/dev/tty': No such device or address
Traceback (most recent call last):
  File "/builds/rpatterson/python-project-structure/./.tox/build/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/twine/__main__.py", line 33, in main
    error = cli.dispatch(sys.argv[1:])
  File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/twine/cli.py", line 123, in dispatch
    return main(args.args)
  File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/twine/commands/upload.py", line 198, in main
    return upload(upload_settings, parsed_args.dists)
  File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/twine/commands/upload.py", line 123, in upload
    packages_to_upload = [
  File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/twine/commands/upload.py", line 124, in <listcomp>
    _make_package(filename, signatures, upload_settings) for filename in uploads
  File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/twine/commands/upload.py", line 83, in _make_package
    package.sign(upload_settings.sign_with, upload_settings.identity)
  File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/twine/package.py", line 217, in sign
    self.run_gpg(gpg_args)
  File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/twine/package.py", line 224, in run_gpg
    subprocess.check_call(gpg_args)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('gpg', '--detach-sign', '-a', './dist/python_project_structure-0.8.5-py3-none-any.whl')' returned non-zero exit status 2.
make: *** [Makefile:621: release-python] Error 1

This reverts commit 9984d546b58bcd29fe62eb5ab3ed3284c1b8d4ab.