ci(github): Avoid repository mirroring push race
I'm assuming this happened because GitLab repository mirroring pushed the bump commit to
GitHub very quickly between the time that the `$ git push ...` running in CI had a
chance to finish with the first push URL and move onto the second.  I haven't seen this
before so it must be pretty unlikely but no reason to duplicate repository mirroring
anyways:

+ git push --no-verify --tags origin HEAD:develop
remote:
remote: To create a merge request for develop, visit:
remote:   https://gitlab.com/rpatterson/prunerr/-/merge_requests/new?merge_request%5Bsource_branch%5D=develop
remote:
To https://gitlab.com/rpatterson/prunerr.git/
   dfd0e8b..234360d  HEAD -> develop
 * [new tag]         v1.1.0b23 -> v1.1.0b23
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/rpatterson/prunerr.git
 ! [remote rejected] HEAD -> develop (cannot lock ref 'refs/heads/develop': is at 234360de2032c29f437c59c4bb7f6c2484b043b5 but expected dfd0e8b132f66f575b46ba69472a242045b19664)
 ! [remote rejected] v1.1.0b23 -> v1.1.0b23 (failed)
error: failed to push some refs to 'https://github.com/rpatterson/prunerr.git'
make: *** [Makefile:627: release-python] Error 1