build(py): More correct pkg version lookup
Discovered while testing `$ pyproject-build --no-isolation`.  The first error was:

     ModuleNotFoundError: No module named 'src'

When the `src.` prefix is removed, then the error was:

      File "/home/rpatterson/src/media/prunerr/src/prunerr/__init__.py", line 20, in <module>
        import argcomplete
    ModuleNotFoundError: No module named 'argcomplete'

So avoid unnecessary imports by specifying the full, direct import path.