ci(docker): Don't require secret on unprotected
    + getent group docker
    + cut -d : -f 3
    + mkdir -pv var/log/
    + set +x
    ERROR: PROJECT_GITHUB_PAT missing from ./.env or CI secrets
    make: *** [Makefile:1343: var/log/docker-login-GITHUB.log] Error 1