ci(release): Missing release notes references
    + docker compose run --rm python-project-structure-devel tox exec --no-recreate-pkg --skip-pkg-install -e py310 -- towncrier check --compare-with origin/develop
    py310: skip building and installing the package
    py310: freeze> python -m pip freeze --all
    py310: argcomplete==3.0.5,astroid==2.15.1,attrs==22.2.0,autoflake==1.7.8,autopep8==2.0.2,bandit==1.7.5,black==23.1.0,build==0.10.0,certifi==2022.12.7,charset-normalizer==3.1.0,click==8.1.3,click-default-group==1.2.2,colorama==0.4.6,commonmark==0.9.1,coverage==7.2.2,dill==0.3.6,docutils==0.19,dodgy==0.2.1,exceptiongroup==1.1.1,flake8==2.3.0,flake8-polyfill==1.0.2,future==0.18.3,gitdb==4.0.10,GitPython==3.1.31,idna==3.4,incremental==22.10.0,iniconfig==2.0.0,isort==5.12.0,Jinja2==3.1.2,lazy-object-proxy==1.9.0,mando==0.6.4,MarkupSafe==2.1.2,mccabe==0.7.0,mypy==1.1.1,mypy-extensions==1.0.0,packaging==23.0,pathspec==0.11.1,pbr==5.11.1,pep8==1.7.1,pep8-naming==0.10.0,pip==23.0.1,pip-tools==6.12.3,platformdirs==3.2.0,pluggy==1.0.0,poetry-semver==0.1.0,prospector==1.9.0,pycodestyle==2.10.0,pydantic==1.10.7,pydocstyle==6.3.0,pyflakes==2.5.0,Pygments==2.14.0,pylint==2.17.1,pylint-celery==0.3,pylint-django==2.5.3,pylint-flask==0.6,pylint-plugin-utils==0.7,pyproject_hooks==1.0.0,pyroma==4.2,pytest==7.2.2,PyYAML==6.0,radon==5.1.0,requests==2.28.2,requirements-detector==1.1.0,rich==12.6.0,rstcheck==6.1.2,rstcheck-core==1.0.3,setoptconf-tmp==0.3.1,setuptools==67.4.0,setuptools-scm==7.1.0,shellingham==1.5.0.post1,six==1.16.0,smmap==5.0.0,snowballstemmer==2.2.0,stevedore==5.0.0,toml==0.10.2,tomli==2.0.1,tomlkit==0.11.7,towncrier==22.12.0,trove-classifiers==2023.3.9,typer==0.7.0,types-docutils==0.19.1.7,typing_extensions==4.5.0,urllib3==1.26.15,vulture==2.7,wheel==0.40.0,wrapt==1.15.0,xenon==0.9.0
    py310: commands[0]> towncrier check --compare-with origin/develop
    git produced output while failing:
    fatal: ambiguous argument 'origin/develop...': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'
    Traceback (most recent call last):
      File "/usr/local/src/python-project-structure/.tox/py310/bin/towncrier", line 8, in <module>
        sys.exit(cli())
      File "/usr/local/src/python-project-structure/.tox/py310/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/src/python-project-structure/.tox/py310/lib/python3.10/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
      File "/usr/local/src/python-project-structure/.tox/py310/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/src/python-project-structure/.tox/py310/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/src/python-project-structure/.tox/py310/lib/python3.10/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
      File "/usr/local/src/python-project-structure/.tox/py310/lib/python3.10/site-packages/towncrier/check.py", line 64, in _main
        __main(compare_with, directory, config)
      File "/usr/local/src/python-project-structure/.tox/py310/lib/python3.10/site-packages/towncrier/check.py", line 83, in __main
        files_changed = list_changed_files_compared_to_branch(
      File "/usr/local/src/python-project-structure/.tox/py310/lib/python3.10/site-packages/towncrier/_git.py", line 32, in list_changed_files_compared_to_branch
        output = check_output(
      File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['git', 'diff', '--name-only', 'origin/develop...']' returned non-zero exit status 128.
    py310: exit 1 (0.26 seconds) /usr/local/src/python-project-structure> towncrier check --compare-with origin/develop pid=60
      py310: FAIL code 1 (0.92=setup[0.67]+cmd[0.26] seconds)
      evaluation failed :( (1.19 seconds)
    make: *** [Makefile:405: check-push] Error 1

This reverts commit 337d230c1d5b0de3208ed5c7eb8e949b6054348a.