build(release): Missing GPG signing key in CI
    + git commit --no-verify -S -m 'build(release): Update changelog v0.6.2-beta.1 -> v0.6.2-beta.2'
    error: gpg failed to sign the data
    fatal: failed to write commit object
    make: *** [Makefile:86: build-bump] Error 128