build(release): Existing repo w branch ref fetched
    + git checkout master --
    Switched to branch 'master'
    Your branch is behind 'origin/master' by 43 commits, and can be fast-forwarded.
      (use "git pull" to update your local branch)
    + git push --no-verify --tags github HEAD:master
    To https://github.com/rpatterson/python-project-structure.git
     * [new tag]               v0.8.11 -> v0.8.11
     ! [rejected]              HEAD -> master (non-fast-forward)
    error: failed to push some refs to 'https://github.com/rpatterson/python-project-structure.git'
    hint: Updates were rejected because the tip of your current branch is behind
    hint: its remote counterpart. Integrate the remote changes (e.g.
    hint: 'git pull ...') before pushing again.
    hint: See the 'Note about fast-forwards' in 'git push --help' for details.
    make: *** [Makefile:730: release-bump] Error 1