build(host): Missing reqs, disallow HOME override
    Run entrypoint make -e BUILD_REQUIREMENTS=false PYTHON_MINORS=3.11 build-bump build-wheel check-clean
      entrypoint make -e BUILD_REQUIREMENTS=false PYTHON_MINORS=3.11 build-bump build-wheel check-clean
      shell: sh -e {0}
      env:
        MSYS: winsymlinks:nativestrict
    touch: /github/home/.local/var/log/python-project-structure-host-install.log: No such file or directory
    Error: Process completed with exit code 1.