build(host): Don't assume PGID doesn't exist
    Run entrypoint make -e ./var/log/docker-login-github.log
      entrypoint make -e ./var/log/docker-login-github.log
      shell: sh -e {0}
    addgroup: gid '123' in use
    Error: Process completed with exit code 1.