fix(daemon): Another interrupted request error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 748, in _error_catcher
        yield
      File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 894, in _raw_read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
    urllib3.exceptions.IncompleteRead: IncompleteRead(32562 bytes read, 2739554 more expected)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 820, in generate
        yield from self.raw.stream(chunk_size, decode_content=True)
      File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 1060, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 949, in read
        data = self._raw_read(amt)
      File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 872, in _raw_read
        with self._error_catcher():
      File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
        self.gen.throw(typ, value, traceback)
      File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 772, in _error_catcher
        raise ProtocolError(arg, e) from e
    urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(32562 bytes read, 2739554 more expected)', IncompleteRead(32562 bytes read, 2739554 more expected))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/pdb.py", line 1723, in main
        pdb._runscript(mainpyfile)
      File "/usr/local/lib/python3.10/pdb.py", line 1583, in _runscript
        self.run(statement)
      File "/usr/local/lib/python3.10/bdb.py", line 598, in run
        exec(cmd, globals, locals)
      File "<string>", line 1, in <module>
      File "/usr/local/bin/prunerr", line 8, in <module>
        sys.exit(main())
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 210, in main
        _main(args=args)
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 265, in _main
        if (result := parsed_args.command(runner, **command_kwargs)) is not None:
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 132, in daemon
        runner.daemon(*args, **kwargs)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 307, in daemon
        self._daemon_inner(stages)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 468, in _daemon_inner
        return self.apply_(stages)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 262, in apply_
        if stage_results := self.apply_stage(stage):
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 445, in apply_stage
        if applier_results := prunerr_stage():
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 167, in __call__
        if not operations or not self.items:
      File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 204, in items
        if not (stage_items := list(stage_filter())):
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 280, in filter_seeding
        yield from servarr_download_client.filter_seeding()
      File "/usr/local/src/prunerr/src/prunerr/servarr/downloadclient.py", line 154, in filter_seeding
        for download_item in self.download_client.items:
      File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 171, in items
        for torrent in self.client.get_torrents()
      File "/usr/local/lib/python3.10/site-packages/transmission_rpc/client.py", line 588, in get_torrents
        for x in self._request(RpcMethod.TorrentGet, {"fields": arguments}, ids, timeout=timeout)["torrents"]
      File "/usr/local/lib/python3.10/site-packages/transmission_rpc/client.py", line 263, in _request
        http_data = self._http_query(query, timeout)
      File "/usr/local/lib/python3.10/site-packages/transmission_rpc/client.py", line 213, in _http_query
        r = self._http_session.post(
      File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
        return self.request("POST", url, data=data, json=json, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 746, in send
        r.content
      File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 902, in content
        self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
      File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 822, in generate
        raise ChunkedEncodingError(e)
    requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(32562 bytes read, 2739554 more expected)', IncompleteRead(32562 bytes read, 2739554 more expected))