fix(upgraded): Broken ignored downloading items
If a release under the ``**/downloads/**`` directory has been ignored, it's no longer in
the Servarr queue but Prunerr didn't move it because its status was still
`downloading`. Then the `uppgraded` stage would fail because it has no queue record:

    DEBUG:prunerr.servarr:Requesting Sonarr 'queue' page 1 with params: {}
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/pdb.py", line 1723, in main
        pdb._runscript(mainpyfile)
      File "/usr/local/lib/python3.10/pdb.py", line 1583, in _runscript
        self.run(statement)
      File "/usr/local/lib/python3.10/bdb.py", line 598, in run
        exec(cmd, globals, locals)
      File "<string>", line 1, in <module>
      File "/usr/local/bin/prunerr", line 8, in <module>
        sys.exit(main())
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 229, in main
        _main(args=args)
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 276, in _main
        if (result := parsed_args.command(runner, **command_kwargs)) is not None:
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 101, in apply_
        return runner.apply_(*args, **kwargs)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 255, in apply_
        if stage_results := self.apply_stage(stage):
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 481, in apply_stage
        if applier_results := prunerr_stage():
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 158, in __call__
        break_applier, operation_results = operation()
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 224, in __call__
        for item in self.items:
      File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 285, in items
        for item in self.stage.items
      File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 187, in items
        if not (stage_items := list(stage_filter())):
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 290, in filter_upgraded
        for imported_release in item.release.filter_upgraded():
      File "/usr/local/src/prunerr/src/prunerr/servarr/release.py", line 236, in filter_upgraded
        if self.root_item is None:  # pragma: no cover
      File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/usr/local/src/prunerr/src/prunerr/servarr/release.py", line 89, in root_item
        for queue_record in self.queue:
    TypeError: 'NoneType' object is not iterable

So change the `seeding:` stage to also include items with the `downloading` status.

While working on this, I realized that the `stalled:` operation has been effectively
disabled since I used log files to apply the operations in the `queued:` stage only once
per item. It takes time to identify stalled items and Prunerr would apply the `queued:`
operations long before then. So also move `stalled:` to the `all:` stage.