build(release): Tolerate older git versions
Encountered on GitLab CI:

    Executing "step_script" stage of the job script
    Using docker image sha256:27d049ce98db4e55ddfaec6cd98c7c9cfd195bc7e994493776959db33522383b for ruby:2.5 with digest ruby@sha256:ecc3e4f5da13d881a415c9692bb52d2b85b090f38f4ad99ae94f932b3598444b ...
    $ make -e build-bump build-docker
    error: unknown option `show-current'
    usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
       or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
       or: git branch [<options>] [-r] (-d | -D) <branch-name>...
       or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
       or: git branch [<options>] (-c | -C) [<old-branch>] <new-branch>
       or: git branch [<options>] [-r | -a] [--points-at]
       or: git branch [<options>] [-r | -a] [--format]
    Generic options
        -v, --verbose         show hash and subject, give twice for upstream branch
        -q, --quiet           suppress informational messages
        -t, --track           set up tracking mode (see git-pull(1))
        -u, --set-upstream-to <upstream>
                              change the upstream info
        --unset-upstream      Unset the upstream info
        --color[=<when>]      use colored output
        -r, --remotes         act on remote-tracking branches
        --contains <commit>   print only branches that contain the commit
        --no-contains <commit>
                              print only branches that don't contain the commit
        --abbrev[=<n>]        use <n> digits to display SHA-1s
    Specific git-branch actions:
        -a, --all             list both remote-tracking and local branches
        -d, --delete          delete fully merged branch
        -D                    delete branch (even if not merged)
        -m, --move            move/rename a branch and its reflog
        -M                    move/rename a branch, even if target exists
        -c, --copy            copy a branch and its reflog
        -C                    copy a branch, even if target exists
        -l, --list            list branch names
        --create-reflog       create the branch's reflog
        --edit-description    edit the description for the branch
        -f, --force           force creation, move/rename, deletion
        --merged <commit>     print only branches that are merged
        --no-merged <commit>  print only branches that are not merged
        --column[=<style>]    list branches in columns
        --sort <key>          field name to sort on
        --points-at <object>  print only branches of the object
        -i, --ignore-case     sorting and filtering are case insensitive
        --format <format>     format to use for the output