ci(github): Missing CI secret, maybe docker login
    + make -e ./var/log/docker-login-GITHUB.log
    make[2]: Entering directory '/__w/python-project-structure/python-project-structure'
    + mkdir -pv var/log/
    + set +x
    make[2]: *** [Makefile:1183: var/log/docker-login-GITHUB.log] Error 1
    ERROR: PROJECT_GITHUB_PAT missing from ./.env or CI secrets