fix(docker): Wrong ownership for docker volumes
When the docker daemon creates volume sources that don't already exist, they're owned by
`root` so every volume that needs to be accessible to the `USER`/`PUID` should be
created *before* docker runs any containers with those volumes.

Addresses
https://github.com/rpatterson/python-project-structure/actions/runs/3404555863/jobs/5661875857:

    ...
    [40] /usr/local/src/python-project-structure$ /usr/local/src/python-project-structure/.tox/.package/bin/python /usr/local/lib/python3.11/site-packages/tox/helper/build_requires.py setuptools.build_meta '' '' >.tox/.package/log/.package-2.log
    error: [Errno 13] Permission denied
    ERROR: invocation failed (exit code 1), logfile: /usr/local/src/python-project-structure/.tox/.package/log/.package-2.log
    ================================== log start ===================================
    running egg_info

    =================================== log end ====================================
    ERROR: FAIL could not package project - v = InvocationError("/usr/local/src/python-project-structure/.tox/.package/bin/python /usr/local/lib/python3.11/site-packages/tox/helper/build_requires.py setuptools.build_meta '' ''", 1)
    2
    make[1]: *** [Makefile:128: var/log/docker-build.log] Error 2
    make[1]: *** Deleting file 'var/log/docker-build.log'
    make: *** [Makefile:78: upgrade] Error 2
    Error: Process completed with exit code 2.