fix(upgraded): Wrong release queue records type
    DEBUG:prunerr.operations:Filtering items for: <PrunerrStage name='upgraded' applier=<PrunerrDownloadClient name='MoodySalon'>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/pdb.py", line 1723, in main
        pdb._runscript(mainpyfile)
      File "/usr/local/lib/python3.10/pdb.py", line 1583, in _runscript
        self.run(statement)
      File "/usr/local/lib/python3.10/bdb.py", line 598, in run
        exec(cmd, globals, locals)
      File "<string>", line 1, in <module>
      File "/usr/local/bin/prunerr", line 8, in <module>
        sys.exit(main())
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 229, in main
        _main(args=args)
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 284, in _main
        if (result := parsed_args.command(runner, **command_kwargs)) is not None:
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 132, in daemon
        runner.daemon(*args, **kwargs)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 345, in daemon
        self._daemon_inner(stages)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 506, in _daemon_inner
        return self.apply_(stages)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 263, in apply_
        if stage_results := self.apply_stage(stage):
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 483, in apply_stage
        if applier_results := prunerr_stage():
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 151, in __call__
        if self.config and not self.items:
      File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 193, in items
        if not (stage_items := list(stage_filter())):
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 295, in filter_upgraded
        for imported_release in item.release.filter_upgraded():
      File "/usr/local/src/prunerr/src/prunerr/servarr/release.py", line 264, in filter_upgraded
        if self.root_item is None:  # pragma: no cover
      File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/usr/local/src/prunerr/src/prunerr/servarr/release.py", line 112, in root_item
        for queue_record in self.queue:
    TypeError: 'NoneType' object is not iterable