build(docker): More correct tox venv activation
Without the `VIRTUAL_ENV` environment variable set, the python3.7 image variant was
failing.  The older version of tox in that image didn't identify that the virtual
environment was activated and thus thought the `base_python` didn't match and thus tried
to recreate the virtual environment by removing it and then invoking `$ python -m
virtualenv` but this older version of `$ tox` tried to do that using the python it just
deleted resulting in a very inscrutable error:

    py37 start: getenv /usr/local/src/python-project-structure/.tox/py37
    py37 cannot reuse: attr base_resolved_python_path '/usr/local/bin/python'!='/usr/local/src/python-project-structure/.tox/py37/bin/python'
    py37 recreate: /usr/local/src/python-project-structure/.tox/py37
      removing /usr/local/src/python-project-structure/.tox/py37
    setting PATH=/usr/local/src/python-project-structure/.tox/py37/bin:/usr/local/src/python-project-structure/.tox/py37/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ERROR: invocation failed (exit code 2)
    ERROR: InvocationError for command /usr/local/src/python-project-structure/.tox/py37/bin/python -m virtualenv --no-download --python /usr/local/src/python-project-structure/.tox/py37/bin/python py37 (exited with code 2)
    py37 finish: getenv /usr/local/src/python-project-structure/.tox/py37 after 0.17 seconds
    _______________________________________ summary ________________________________________
    ERROR:   py37: InvocationError for command /usr/local/src/python-project-structure/.tox/py37/bin/python -m virtualenv --no-download --python /usr/local/src/python-project-structure/.tox/py37/bin/python py37 (exited with code 2)