fix(transmission): UndefinedError uploadedEver
I only got this exception when editing the user's configuration file which makes me
concerned about why I didn't get it withe the example:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/pdb.py", line 1723, in main
        pdb._runscript(mainpyfile)
      File "/usr/local/lib/python3.10/pdb.py", line 1583, in _runscript
        self.run(statement)
      File "/usr/local/lib/python3.10/bdb.py", line 598, in run
        exec(cmd, globals, locals)
      File "<string>", line 1, in <module>
      File "/usr/local/bin/prunerr", line 8, in <module>
        sys.exit(main())
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 229, in main
        _main(args=args)
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 284, in _main
        if (result := parsed_args.command(runner, **command_kwargs)) is not None:
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 103, in apply_
        return runner.apply_(*args, **kwargs)
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 258, in apply_
        if stage_results := self.apply_stage(stage):
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 482, in apply_stage
        if applier_results := prunerr_stage():
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 158, in __call__
        break_applier, operation_results = operation()
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 217, in __call__
        for item_idx, item in enumerate(self.items):
      File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 295, in items
        operation_items.sort(
      File "/usr/local/src/prunerr/src/prunerr/operations.py", line 296, in <lambda>
        key=lambda item: self.config[OPERATION_SORT].render(
      File "/usr/local/lib/python3.10/site-packages/jinja2/nativetypes.py", line 112, in render
        return self.environment.handle_exception()
      File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/usr/local/lib/python3.10/site-packages/jinja2/nativetypes.py", line 25, in native_concat
        head = list(islice(values, 2))
      File "<template>", line 19, in top-level template code
    jinja2.exceptions.UndefinedError: 'prunerr.downloaditem.PrunerrDownloadItem object' has no attribute 'uploadedEver'

Regardless, it's best to use the Python API first, so update all `camelCase` attributes to
the `snake_case` properties provided by `transmission_rpc`.