build(release): Fix silent missing version tag err
    + tox exec --no-recreate-pkg --skip-pkg-install -e build -- python ./bin/cz-check-bump
    build: freeze> python -m pip freeze --all
    build: argcomplete==2.0.6,bleach==6.0.0,certifi==2022.12.7,cffi==1.15.1,cfgv==3.3.1,charset-normalizer==2.1.1,colorama==0.4.6,commitizen==2.42.1,cryptography==40.0.0,decli==0.5.2,distlib==0.3.6,docutils==0.19,filelock==3.10.4,identify==2.5.21,idna==3.4,importlib-metadata==6.1.0,jaraco.classes==3.2.3,jeepney==0.8.0,Jinja2==3.1.2,keyring==23.13.1,markdown-it-py==2.2.0,MarkupSafe==2.1.2,mdurl==0.1.2,more-itertools==9.1.0,nodeenv==1.7.0,packaging==23.0,pip==23.0.1,pkginfo==1.9.6,platformdirs==3.1.1,pre-commit==3.2.0,prompt-toolkit==3.0.38,pycparser==2.21,Pygments==2.14.0,PyYAML==6.0,questionary==1.10.0,readme-renderer==37.3,requests==2.28.2,requests-toolbelt==0.10.1,rfc3986==2.0.0,rich==13.3.2,SecretStorage==3.3.3,setuptools==67.4.0,six==1.16.0,termcolor==2.2.0,tomlkit==0.11.6,twine==4.0.2,typing_extensions==4.5.0,urllib3==1.26.15,virtualenv==20.21.0,wcwidth==0.2.6,webencodings==0.5.1,wheel==0.38.4,zipp==3.15.0
    build: commands[0]> python ./bin/cz-check-bump
    Traceback (most recent call last):
      File "/__w/python-project-structure/python-project-structure/./bin/cz-check-bump", line 75, in <module>
        main()
      File "/__w/python-project-structure/python-project-structure/./bin/cz-check-bump", line 56, in main
        commits = git.get_commits(current_tag_version)
      File "/__w/python-project-structure/python-project-structure/.tox/build/lib/python3.10/site-packages/commitizen/git.py", line 111, in get_commits
        git_log_entries = _get_log_as_str_list(start, end, args)
      File "/__w/python-project-structure/python-project-structure/.tox/build/lib/python3.10/site-packages/commitizen/git.py", line 253, in _get_log_as_str_list
        raise GitCommandError(c.err)
    commitizen.exceptions.GitCommandError: fatal: ambiguous argument 'v0.0.0..HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

    build: exit 1 (0.36 seconds) /__w/python-project-structure/python-project-structure> python ./bin/cz-check-bump pid=1200
      build: FAIL code 1 (1.01=setup[0.65]+cmd[0.36] seconds)
      evaluation failed :( (1.28 seconds)