ci(cache): Avoid tox requirements recreation errs
I've run into this error several times when `./**/requirements*.txt` change.  The error
recurs when re-running the job and doesn't recur when the caches are cleared by bumping
the cache version.  Between that and what I can tell from the tracebacks it sure seems
like there's something broken with caching the `./.tox/*/` virtual environments.  From
my understanding caching these *should* work and I don't fully understand why it's not.
I'm also on the fence, however, about re-using virtual environments in CI/CD anyways
because clean builds are better in CI/CD where the run-times aren't increased too much.
So lets try this out and see how run-times are affected:

    + tox exec --no-recreate-pkg --skip-pkg-install -e py311 -- python -c ''
    py311: recreate env because requirements removed: types-docutils==0.19.1.4
    py311: remove tox env folder /usr/local/src/python-project-structure/.tox/py311
    py311: internal error
    Traceback (most recent call last):
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/api.py", line 249, in setup
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/python/runner.py", line 107, in _setup_env
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/python/runner.py", line 111, in _install_deps
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/api.py", line 96, in _install
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/python/pip/pip_install.py", line 90, in install
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/python/pip/pip_install.py", line 135, in _install_requirement_file
    tox.tox_env.errors.Recreate: requirements removed: types-docutils==0.19.1.4
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/session/cmd/run/single.py", line 45, in _evaluate
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/api.py", line 255, in setup
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/python/runner.py", line 106, in _setup_env
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/python/api.py", line 198, in _setup_env
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/python/api.py", line 205, in ensure_python_env
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/api.py", line 129, in create_python_env
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/virtualenv/run/session.py", line 42, in run
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/virtualenv/run/session.py", line 49, in _create
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/virtualenv/create/creator.py", line 149, in run
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 97, in create
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/virtualenv/create/via_global_ref/api.py", line 83, in create
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/virtualenv/create/via_global_ref/api.py", line 86, in install_patch
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/virtualenv/create/via_global_ref/builtin/cpython/cpython3.py", line 25, in env_patch_text
      File "/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/virtualenv/create/via_global_ref/api.py", line 98, in env_patch_text
      File "/usr/local/lib/python3.11/pathlib.py", line 1058, in read_text
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
        return io.open(self, mode, buffering, encoding, errors, newline)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/src/python-project-structure/.tox/py311/lib/python3.11/site-packages/virtualenv/create/via_global_ref/_virtualenv.py'
      py311: FAIL code 2 (0.44 seconds)
      evaluation failed :( (0.51 seconds)
    make[1]: *** [Makefile:696: var/log/tox/py311/build.log] Error 2