ci(github): GitHub Actions artifact name clash
    Run actions/upload-artifact@master
      with:
        name: test-coverage-lint-reports
        path: ./build/reports/

        if-no-files-found: warn
        compression-level: 6
        overwrite: false
      env:
        PUID: 1001
        PGID: 1001
        PROJECT_NAMESPACE: rpatterson
        PROJECT_NAME: prunerr
        GPG_PASSPHRASE: ***
        GPG_SIGNING_PRIVATE_KEY: ***

        DOCKER_PASS: ***
        PROJECT_GITHUB_PAT: ***
        CI_IS_FORK: true
        DEBUG: true
    /usr/bin/docker exec  36c67dd5132f50bb13adbb5c6d7980ee8abfc1ba544cc15ef1aa107e5ede25dd sh -c "cat /etc/*release | grep ^ID"
    With the provided path, there will be 37 files uploaded
    Artifact name is valid!
    Root directory input is valid!
    Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run