build(requirements): Python 2 compatibility
Couldn't reproduce this locally, but it popped up in CI:

  $ python setup.py --version
  Traceback (most recent call last):
    File "setup.py", line 58, in <module>
      entry_points=dict(console_scripts=["python-main-wrapper=mainwrapper:main"]),
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
      _install_setup_requires(attrs)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
      replace_conflicting=True,
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
      replace_conflicting=replace_conflicting
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
      return self.obtain(req, installer)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
      return installer(requirement)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
      return cmd.easy_install(req)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
      run_setup(setup_script, args)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
      raise
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/contextlib.py", line 35, in __exit__
      self.gen.throw(type, value, traceback)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/contextlib.py", line 35, in __exit__
      self.gen.throw(type, value, traceback)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
      saved_exc.resume()
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
      six.reraise(type, exc, self._tb)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
      yield saved
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
      _execfile(setup_script, ns)
    File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/setuptools/sandbox.py", line 44, in _execfile
      code = compile(script, filename, 'exec')
    File "/tmp/easy_install-2toT61/setuptools_scm-6.3.2/setup.py", line 22
      f"{type(self).__name__} is forbidden, "
                                          ^
SyntaxError: invalid syntax

The [`setuptools_scm` changelog is pretty clear when support for Python 2 was
dropped](https://github.com/pypa/setuptools_scm/blob/main/CHANGELOG.rst#v600) so we
might as well fix this even if I can't reproduce locally.