build(upgrade): Missing remote ref on shallow
Such as on CI/CD:

    + git push --set-upstream --force-with-lease origin HEAD:develop-upgrade
    To https://gitlab.com/rpatterson/python-project-structure.git/
     ! [rejected]        HEAD -> develop-upgrade (stale info)
    error: failed to push some refs to 'https://gitlab.com/rpatterson/python-project-structure.git/'
    make: *** [Makefile:563: upgrade-branch] Error 1