build(host): Missing ~/.gitconfig in tox exec cmds
I forgot that tox strips environment variables by default:

    + tox exec --no-recreate-pkg --skip-pkg-install -e build -- cz --debug bump --check-consistency --no-verify --prerelease beta --gpg-sign --yes
    build: freeze> python -m pip freeze --all
    build: argcomplete==2.0.0,bleach==5.0.1,certifi==2022.12.7,cffi==1.15.1,cfgv==3.3.1,charset-normalizer==2.1.1,colorama==0.4.6,commitizen==2.39.1,commonmark==0.9.1,cryptography==39.0.0,decli==0.5.2,distlib==0.3.6,docutils==0.19,filelock==3.9.0,identify==2.5.12,idna==3.4,importlib-metadata==6.0.0,jaraco.classes==3.2.3,jeepney==0.8.0,Jinja2==3.1.2,keyring==23.13.1,MarkupSafe==2.1.1,more-itertools==9.0.0,nodeenv==1.7.0,packaging==22.0,pip==22.3.1,pkginfo==1.9.3,platformdirs==2.6.2,pre-commit==2.21.0,prompt-toolkit==3.0.36,pycparser==2.21,Pygments==2.14.0,PyYAML==6.0,questionary==1.10.0,readme-renderer==37.3,requests==2.28.1,requests-toolbelt==0.10.1,rfc3986==2.0.0,rich==13.0.0,SecretStorage==3.3.3,setuptools==65.6.3,six==1.16.0,termcolor==2.2.0,tomlkit==0.11.6,twine==4.0.2,typing_extensions==4.4.0,urllib3==1.26.13,virtualenv==20.17.1,wcwidth==0.2.5,webencodings==0.5.1,wheel==0.38.4,zipp==3.11.0
    build: commands[0]> cz --debug bump --check-consistency --no-verify --prerelease beta --gpg-sign --yes
    build(release): Version 0.9.0b1 → 0.9.0b2
    [actions skip]
    tag to create: v0.9.0b2
    2nd git.commit error: "Author identity unknown
    *** Please tell me who you are.
    Run
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
    to set your account's default identity.
    Omit --global to set the identity only in this repository.
    fatal: unable to auto-detect email address (got 'runner@runner-zxwgkjap-project-41587336-concurrent-0.(none)')"
    Traceback (most recent call last):
      File "/builds/rpatterson/python-project-structure/.tox/build/bin/cz", line 8, in <module>
        sys.exit(main())
      File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/commitizen/cli.py", line 407, in main
        args.func(conf, vars(args))()
      File "/builds/rpatterson/python-project-structure/.tox/build/lib/python3.10/site-packages/commitizen/commands/bump.py", line 286, in __call__
        raise BumpCommitFailedError(f'2nd git.commit error: "{c.err.strip()}"')
    commitizen.exceptions.BumpCommitFailedError: 2nd git.commit error: "Author identity unknown
    *** Please tell me who you are.
    Run
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
    to set your account's default identity.
    Omit --global to set the identity only in this repository.
    fatal: unable to auto-detect email address (got 'runner@runner-zxwgkjap-project-41587336-concurrent-0.(none)')"
    build: exit 6 (0.45 seconds) /builds/rpatterson/python-project-structure> cz --debug bump --check-consistency --no-verify --prerelease beta --gpg-sign --yes pid=634
      build: FAIL code 6 (1.14=setup[0.69]+cmd[0.45] seconds)
      evaluation failed :( (1.43 seconds)
    make: *** [Makefile:183: build-bump] Error 6

I came up with this list by auditing all environment variables referenced in:

- `{env:...}` in `./tox.ini`
- `environment: ...` in `./docker-compose*.yml`
- `^export ...` in `./Makefile`
- `$ docker compose run -e ...` in `./Makefile`