fix(retry): Tolerate more transmission_rpc excepts
Encountered when I restarted the download client:

    DEBUG:prunerr.downloadclient:Retrieving list of download items from download client: http://transmission:secret@localhost:9091/transmission/
    ERROR:transmission-rpc:Error: Expecting ',' delimiter: line 1 column 4810602 (char 4810601)
    ERROR:transmission-rpc:Request: "{'tag': 1, 'method': 'torrent-get', 'arguments': {'fields': ['activityDate', 'addedDate', 'comment', 'corruptEver', 'creator', 'dateCreated', 'desiredAvailable', 'doneDate', 'downloadedEver', 'downloadLimit', 'error', 'errorString', 'eta', 'files', 'hashString', 'haveUnchecked', 'haveValid', 'id', 'isPrivate', 'leftUntilDone', 'manualAnnounceTime', 'maxConnectedPeers', 'name', 'peersConnected', 'peersFrom', 'peersGettingFromUs', 'peersSendingToUs', 'pieceCount', 'pieceSize', 'priorities', 'rateDownload', 'rateUpload', 'recheckProgress', 'sizeWhenDone', 'startDate', 'status', 'trackers', 'totalSize', 'uploadedEver', 'uploadLimit', 'uploadRatio', 'wanted', 'webseeds', 'webseedsSendingToUs', 'peers', 'downloadDir', 'bandwidthPriority', 'downloadLimited', 'fileStats', 'honorsSessionLimits', 'peer-limit', 'percentDone', 'pieces', 'seedRatioLimit', 'seedRatioMode', 'torrentFile', 'uploadLimited', 'magnetLink', 'metadataPercentComplete', 'trackerStats', 'isFinished', 'seedIdleLimit', 'seedIdleMode', 'isStalled', 'queuePosition', 'etaIdle', 'secondsDownloading', 'secondsSeeding', 'labels', 'editDate']}}"
    ERROR:transmission-rpc:HTTP data: "{"arguments":{"torrents":[...
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 236, in _request
        data: dict = json.loads(http_data)
                     ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
                   ^^^^^^^^^^^^^^^^^^^^^^
    json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 4810602 (char 4810601)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/pdb.py", line 1768, in main
        pdb._run(target)
      File "/usr/local/lib/python3.11/pdb.py", line 1646, in _run
        self.run(target.code)
      File "/usr/local/lib/python3.11/bdb.py", line 597, in run
        exec(cmd, globals, locals)
      File "<string>", line 1, in <module>
      File "/usr/local/bin/prunerr", line 8, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 213, in main
        results = parsed_args.command(runner, **command_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 140, in daemon
        return runner.daemon(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 301, in daemon
        self.update()
      File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in wrapped_f
        return self(f, *args, **kw)
               ^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 406, in __call__
        do = self.iter(retry_state=retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 351, in iter
        return fut.result()
               ^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 409, in __call__
        result = fn(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 115, in update
        download_clients[download_client_url].update(download_client_config)
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 109, in update
        for torrent in self.client.get_torrents()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 540, in get_torrents
        return list(self._request("torrent-get", {"fields": arguments}, ids, timeout=timeout).values())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/transmission_rpc/client.py", line 241, in _request
        raise ValueError from error
    ValueError