build(py): Workaround arrapi old API usage
Only happens in the Docker Python 3.12 image, I'm assuming because I must have
`setuptools` installed into the system Python 3.12 locally:

    ModuleNotFoundError: No module named 'pkg_resources'