ci(env): Missing template env exports
    + make -e ./var/log/docker-login-GITHUB.log
    make[2]: Entering directory '/__w/python-project-structure/python-project-structure'
    + mkdir -pv var/log/
    + set +x
    ERROR: PROJECT_GITHUB_PAT missing from ./.env or CI secrets
    make[2]: *** [Makefile:1206: var/log/docker-login-GITHUB.log] Error 1