build(make): Install required command if missing
Encountered the need for this on GitLab CI/CD:

    + make PUID=0 PGID=0 template=.env.in target=.env expand-template
    make[1]: Entering directory '/builds/rpatterson/python-project-structure'
    bash: line 8: envsubst: command not found
    make[1]: *** [Makefile:263: expand-template] Error 127
    make[1]: Leaving directory '/builds/rpatterson/python-project-structure'
    make: *** [Makefile:324: .env] Error 2
    make: *** Deleting file '.env'
    Cleaning up project directory and file based variables
    ERROR: Job failed: exit code 1