build(tox): Mistakenly installing tox in a tox env
Exposed under Python3.7:

    py37 start: getenv /usr/local/src/python-project-structure/.tox/py37
    py37 cannot reuse: attr base_resolved_python_path '/usr/local/bin/python'!='/usr/local/src/python-project-structure/.tox/py37/bin/python'
    py37 recreate: /usr/local/src/python-project-structure/.tox/py37
      removing /usr/local/src/python-project-structure/.tox/py37
    setting PATH=/usr/local/src/python-project-structure/.tox/py37/bin:/usr/local/src/python-project-structure/.tox/py37/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ERROR: invocation failed (exit code 2)
    ERROR: InvocationError for command /usr/local/src/python-project-structure/.tox/py37/bin/python -m virtualenv --no-download --python /usr/local/src/python-project-structure/.tox/py37/bin/python py37 (exited with code 2)
    py37 finish: getenv /usr/local/src/python-project-structure/.tox/py37 after 0.17 seconds
    _______________________________________ summary ________________________________________
    ERROR:   py37: InvocationError for command /usr/local/src/python-project-structure/.tox/py37/bin/python -m virtualenv --no-download --python /usr/local/src/python-project-structure/.tox/py37/bin/python py37 (exited with code 2)

The older version of tox, whose dependencies are compatible with Python 3.7, notices
that the tox installation is now from a different tox env than when it was originally
created and thus tries to recreate the env.  Unfortunately, it doesn't recognize that
it's deleting its own env and fails inscrutably.