build(release): Release tool requires package path
Turns out that `$ towncrier` imports the package and thus will fail if used from the `$
tox -e build` virtualenv:

    + ./.tox/build/bin/towncrier build --version 1.0.0b0 --draft --yes
    Loading template...
    Finding news fragments...
    Rendering news fragments...
    Traceback (most recent call last):
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/towncrier/_project.py", line 19, in _get_package
	module = import_module(package)
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
	return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'pythonprojectstructure'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/rpatterson/src/devel/python-project-structure/./.tox/build/bin/towncrier", line 8, in <module>
	sys.exit(cli())
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
	return self.main(*args, **kwargs)
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/click/core.py", line 1055, in main
	rv = self.invoke(ctx)
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
	return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
	return ctx.invoke(self.callback, **ctx.params)
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/click/core.py", line 760, in invoke
	return __callback(*args, **kwargs)
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/towncrier/build.py", line 89, in _main
	return __main(
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/towncrier/build.py", line 156, in __main
	project_name = get_project_name(
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/towncrier/_project.py", line 65, in get_project_name
	module = _get_package(package_dir, package)
      File "/home/rpatterson/src/devel/python-project-structure/.tox/build/lib/python3.10/site-packages/towncrier/_project.py", line 26, in _get_package
	module = import_module(package)
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
	return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/rpatterson/src/devel/python-project-structure/src/pythonprojectstructure/__init__.py", line 13, in <module>
	import tenacity
    ModuleNotFoundError: No module named 'tenacity'
    make: *** [Makefile:122: build-bump] Error 1

Install and run `$ towncrier` from the `$ tox -e py3` virtualenv instead.