fix(verify): Missing download client RPC client
    INFO:prunerr.downloadclient:Resuming verified download items:
      <Torrent 380 "...">
    Traceback (most recent call last):
      File "/usr/local/src/prunerr/.tox/py311/bin/prunerr", line 8, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 214, in main
        _main(args=args)
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 259, in _main
        result = parsed_args.command(runner, **command_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/__init__.py", line 157, in daemon
        return runner.daemon(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 304, in daemon
        self.resume_verified_items()
      File "/usr/local/src/prunerr/src/prunerr/runner.py", line 454, in resume_verified_items
        resumed_items = list(download_client.resume_verified_items().values())
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/src/prunerr/src/prunerr/downloadclient.py", line 373, in resume_verified_items
        self.client.start_torrent(list(verified_items.keys()))
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'start_torrent'