ci(cache): Attempt workaround stale venv failure
I've also seen this issue locally a few times and just worked around it by deleting
`./.tox/`.  I have no concrete memory of what conditions correspond to this error, but I
vaguely recall it being related to updated/changed requirements.  OTOH, it could be
reproduced by parallel execution in containers locally and by shared cache on CI.  Now
that it's rearing its ugly head in CI, I'll have to run this to ground the next time I
run into it locally.  In the meantime, I confirmed the hypothesis that clearing CI cache
works around the issue by clearing the cache in the GitLab web UI and this change does
the same for GitHub Actions.

    + tox run --no-recreate-pkg --skip-pkg-install -e py38 --notest
    py38: recreate env because requirements removed: types-docutils==0.19.1.6 tomlkit==0.11.6 argcomplete==3.0.4 astroid==2.15.0 platformdirs==3.1.1
    py38: remove tox env folder /usr/local/src/python-project-structure/.tox/py38
    py38: internal error
    Traceback (most recent call last):
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/api.py", line 249, in setup
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/python/runner.py", line 107, in _setup_env
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/python/runner.py", line 111, in _install_deps
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/api.py", line 96, in _install
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/python/pip/pip_install.py", line 90, in install
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/python/pip/pip_install.py", line 135, in _install_requirement_file
    tox.tox_env.errors.Recreate: requirements removed: types-docutils==0.19.1.6 tomlkit==0.11.6 argcomplete==3.0.4 astroid==2.15.0 platformdirs==3.1.1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/session/cmd/run/single.py", line 45, in _evaluate
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/api.py", line 255, in setup
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/python/runner.py", line 106, in _setup_env
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/python/api.py", line 198, in _setup_env
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/python/api.py", line 205, in ensure_python_env
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/tox/tox_env/python/virtual_env/api.py", line 129, in create_python_env
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/virtualenv/run/session.py", line 42, in run
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/virtualenv/run/session.py", line 49, in _create
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/virtualenv/create/creator.py", line 149, in run
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 97, in create
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/virtualenv/create/via_global_ref/api.py", line 83, in create
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/virtualenv/create/via_global_ref/api.py", line 86, in install_patch
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/virtualenv/create/via_global_ref/builtin/cpython/cpython3.py", line 25, in env_patch_text
      File "/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/virtualenv/create/via_global_ref/api.py", line 98, in env_patch_text
      File "/usr/local/lib/python3.8/pathlib.py", line 1236, in read_text
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
      File "/usr/local/lib/python3.8/pathlib.py", line 1222, in open
        return io.open(self, mode, buffering, encoding, errors, newline,
      File "/usr/local/lib/python3.8/pathlib.py", line 1078, in _opener
        return self._accessor.open(self, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/virtualenv/create/via_global_ref/_virtualenv.py'
    /usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/setuptools_scm/git.py:135: UserWarning: "/usr/local/src/python-project-structure" is shallow and may cause errors
      warnings.warn(f'"{wd.path}" is shallow and may cause errors')
    /usr/local/src/python-project-structure/.tox/py38/lib/python3.8/site-packages/setuptools_scm/git.py:135: UserWarning: "/usr/local/src/python-project-structure" is shallow and may cause errors
      warnings.warn(f'"{wd.path}" is shallow and may cause errors')
      py38: FAIL code 2 (0.43 seconds)
      evaluation failed :( (0.63 seconds)
    make[1]: *** [Makefile:735: var/log/tox/py38/build.log] Error 2