build(docker): Missing release compose env file
    + docker compose run --rm python-project-structure-devel pyproject-build -s
    open /__w/python-project-structure/python-project-structure/.env: no such file or directory
    make: *** [Makefile:402: release-python] Error 14
    Error: Process completed with exit code 2.